#!/bin/bash
#-----------HEADER-------------------------------------------------------------|
# AUTOR             : Edivan Carvalho <edivancarvalho2008@hotmail.com>
# HOMEPAGE          : https://github.com/edivancarvalho
# DATA DE CRIAÇÃO   : 02/08/2019 às 17:37 
# PROGRAMA          : SO - Fedora 32
# VERSÃO            : 1.0.0
# LICENÇA           : MIT
# PEQUENA DESCRIÇÃO : Instalação de Feramentas de Desenvolvimento 
#
# CHANGELOG :
#
#------------------------------------------------------------------------------|

# Instalação do VirtualBox no fedora32 e 33.
https://www.if-not-true-then-false.com/2010/install-virtualbox-with-yum-on-fedora-centos-red-hat-rhel/
#
# Instalação do virtual box no Debian 10;
 segue o link:
 <https://vitux.com/how-to-install-virtualbox-on-debian-10/>
