#!/bin/bash
#-----------HEADER-------------------------------------------------------------|
# AUTOR             : Edivan Carvalho <edivancarvalho2008@hotmail.com>
# HOMEPAGE          : https://github.com/edivancarvalho
# DATA DE CRIAÇÃO   : 02/08/2019 às 17:37 
# PROGRAMA          : SO - Fedora 32
# VERSÃO            : 1.0.0
# LICENÇA           : MIT
# PEQUENA DESCRIÇÃO : Instalação de Feramentas de Desenvolvimento 
#
# CHANGELOG :
#
#------------------------------------------------------------------------------|
#
# Instalação do virtual box no Debian 10;
 segue o link:
 <https://vitux.com/how-to-install-virtualbox-on-debian-10/>